name: Django-app

on: push

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: clone repo
      uses: actions/checkout@v2

    - name: create python virtual env
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pep8-naming flake8-broken-line flake8-return flake8-isort
        pip install -r api_yamdb/requirements.txt    

    - name: run test flake8 =)
      run: |
        python -m flake8

    - name: run pytest
      run: |
        pytest

  build_and_push_to_docker_hub:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: api_yamdb/
          push: true
          tags: miskivea/yamdb_final:latest

  deploy:
    name: Pull image from Docker Hub to server and run project
    runs-on: ubuntu-latest
    needs: build_and_push_to_docker_hub
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: executing remote ssh commands to deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |            
            sudo docker-compose stop
            sudo docker-compose rm web            
            touch .env
            echo DB_ENGINE=${{ secrets.DB_ENGINE }} >> .env
            echo DB_NAME=${{ secrets.DB_NAME }} >> .env
            echo POSTGRES_USER=${{ secrets.POSTGRES_USER }} >> .env
            echo POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} >> .env
            echo DB_HOST=${{ secrets.DB_HOST }} >> .env
            echo DB_PORT=${{ secrets.DB_PORT }} >> .env
            sudo docker-compose up -d
            

  send_message_tests:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Send message after successful completion of tests
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.MY_TELEGRAM_ID }}
          token: ${{ secrets.ENID_BOT_TOKEN }}
          message: Тесты успешно пройдены!

  send_message_push:
    runs-on: ubuntu-latest
    needs: build_and_push_to_docker_hub
    steps:
      - name: Send message after successful push to Docker Hub
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.MY_TELEGRAM_ID }}
          token: ${{ secrets.ENID_BOT_TOKEN }}
          message: Образ загружен в облако!


  send_message_deploy:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Send message after deploy
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.MY_TELEGRAM_ID }}
          token: ${{ secrets.ENID_BOT_TOKEN }}
          message: Проект задеплоен. ${{ github.workflow }} успешно выполнен!
